In [19]:
from datetime import datetime

# 獲取當前時間
current_time = datetime.now().strftime("%b%d_H%H_M%M_S%S")
current_time

'Mar20_H16_M06_S25'

In [63]:
a = vars()

In [65]:
"x" in a

True

In [66]:
# 檢查變數是否已經宣告
def is_variable_declared(var_name):
    try:
        # 使用 vars() 函式查看當前作用域中的所有變數
        variables = vars()
        return var_name in variables
    except NameError:
        return False

# 測試範例
x = 10
y = 20

print(is_variable_declared('x'))  # 輸出 True，因為變數 x 已經宣告
print(is_variable_declared('y'))  # 輸出 True，因為變數 y 已經宣告
print(is_variable_declared('z'))  # 輸出 False，因為變數 z 尚未宣告


False
False
False


In [ ]:
0.33, 0.6, 0.09
-0.16, 0.6, 0.09
0.33, -0.6, 0.09

-0.16, 0.27, 0.09
0.24, -0.25, 0.09

In [9]:
import random

x_range = [-0.16, 0.33]
# x_range = [-16, 33]
y_range = [-0.6, 0.6]

x_notgood_range = [-0.16, 0.24]
y_notgood_range = [-0.27, 0.27]

for i in range(100):
    # x_range * 100, then random
    x_coor = random.randint(*[x * 100 for x in x_range])
    x_coor = random.randint(*[x * 100 for x in x_range])
    print(x_coor)


4
2
24
4
20
0
-7
12
13
-6
-8
16
20
13
14
19
27
15
-9
-8
25
5
-12
-5
26
-13
16
-2
21
3
-7
28
14
13
9
5
17
10
0
-14
-7
19
-12
-8
10
-6
9
31
17
18
-10
26
12
-6
23
2
18
32
30
19
-5
-10
23
23
-16
-14
-2
14
24
5
-14
27
-5
-8
-2
29
19
7
19
-14
3
-6
24
20
-8
22
10
13
15
-5
-11
30
13
17
-16
-7
-5
6
13
-6


In [16]:
import random

# 指定範圍和間隔
x_min, x_max = -0.16, 0.33
y_min, y_max = -0.6, 0.6
interval = 0.01

# 計算可能的值數量
x_num_values = int((x_max - x_min) / interval) + 1
y_num_values = int((y_max - y_min) / interval) + 1


x_list = [x_min + i * interval for i in range(x_num_values)]
# 抽取隨機數
x_coor = random.choice([x_min + i * interval for i in range(x_num_values)])
y_coor = random.choice([y_min + i * interval for i in range(y_num_values)])

print(x_coor, y_coor)
[x_min + i * interval for i in range(x_num_values)]
x_min + interval *2

0.15 0.5100000000000001


-0.16

In [59]:
import numpy as np

np.random.seed(42)
# 指定範圍和間隔
x_min, x_max = -0.16, 0.33
y_min, y_max = -0.6, 0.6
interval = 0.01

x_min_notgood, x_max_notgood = -0.16, 0.24
y_min_notgood, y_max_notgood = -0.27, 0.27

# 生成抽樣點
x_values = np.round(np.arange(x_min, x_max + interval, interval), 2)
y_values = np.round(np.arange(y_min, y_max + interval, interval), 2)


while True:
    # 隨機抽取一個值
    x_coor = np.random.choice(x_values)
    y_coor = np.random.choice(y_values)
    
    # check boundary
    if (x_min_notgood <= x_coor <= x_max_notgood) and (y_min_notgood <= y_coor <= y_max_notgood):
        print(x_coor, y_coor)
        print("random again")
    else:
        break

print(x_coor, y_coor)


0.22 -0.09
random again
0.12 -0.46


In [41]:
i = 0
while True:
    print(i)
    if i == 10:
        break
    
    i += 1

0
1
2
3
4
5
6
7
8
9
10


In [39]:
x_coor, y_coor

(0.07, 0.36)

In [32]:
x_min_notgood, x_max_notgood = -0.16, 0.24
y_min_notgood, y_max_notgood = -0.27, 0.27


In [33]:
if (x_min_notgood <= x_coor <= x_max_notgood) and (y_min_notgood <= y_coor <= y_max_notgood):
    print("G")

In [4]:
import datetime

# 取得當前的日期和時間
now = datetime.datetime.now()

# 取得月份的英文縮寫表示
month_abbr = now.strftime('%b')

print(f'現在的月份是：{month_abbr}')


現在的月份是：Mar


In [17]:
from tensorboard.backend.event_processing import event_accumulator
import pandas as pd
from tqdm import tqdm
import os

# 指定要读取的事件文件路径
logdir = '/c/Users/yen/code/from_wsl/webots_arm/integration/controllers/train_RL_env/runs/Mar18_11-47-17_SuperWhite3080_arm/events.out.tfevents.1710733637.SuperWhite3080.18304.0'

export_dir = f"{os.path.dirname(logdir)}/training_result.csv"
# 创建 SummaryReader 对象，指定事件文件路径
event_data = event_accumulator.EventAccumulator(logdir)

event_data.Reload()

keys = event_data.scalars.Keys()
print(keys)

df = pd.DataFrame(columns=keys)

for key in tqdm(keys):
    df[key] = pd.DataFrame(event_data.Scalars(key)).value
         
df.to_csv(export_dir)


['Temporal Difference Loss', 'Mean Reward', 'Epsilon', 'Mean Durations']


100%|██████████| 4/4 [00:00<00:00, 61.18it/s]


In [14]:
df = pd.DataFrame(columns=keys)

for key in tqdm(keys):
    df[key] = pd.DataFrame(event_data.Scalars(key)).value


100%|██████████| 4/4 [00:00<00:00, 60.38it/s]


In [15]:
df

Temporal Difference Loss  Mean Reward   Epsilon  Mean Durations
0                     0.000000  -607.364197  0.899579       16.200001
1                    15.899516  -633.516418  0.899155       17.799999
2                    23.516779  -588.451477  0.898730       15.800000
3                    27.245363  -531.200256  0.898306        4.600000
4                    30.757950  -613.241577  0.897882       16.799999
...                        ...          ...       ...             ...
2411                  2.003071  -507.238556  0.304485        1.200000
2412                  4.265377  -513.645569  0.304358        2.400000
2413                  1.234487  -507.496368  0.304231        1.200000
2414                  1.866881  -506.092438  0.304103        1.000000
2415                  4.407290  -509.476624  0.303976        1.600000

[2416 rows x 4 columns]

In [13]:
pd.DataFrame(event_data.Scalars(keys[0])).value

0        0.000000
1       15.899516
2       23.516779
3       27.245363
4       30.757950
          ...    
2411     2.003071
2412     4.265377
2413     1.234487
2414     1.866881
2415     4.407290
Name: value, Length: 2416, dtype: float64

In [16]:
import os

# Specify the path of the file
file_path = '/path/to/your/file.txt'

# Get the directory path of the file
directory_path = os.path.dirname(file_path)

print(directory_path)


/path/to/your


In [12]:

class A:
    def __init__(self) -> None:
        self.apple = 0
        pass

class state:
    def __init__(self, seed) -> None:
        assert type(seed) == int, "Fuck"
        self.arm = 0

ob = state(123)
ob.b = 0
ob.b

a = A()
print(type(a))
print(type(ob))

<class '__main__.A'>
<class '__main__.state'>


In [3]:
import math

# 計算以 10 為底的對數
result = math.log10(100)  # log10 函數表示以 10 為底的對數
print(result)


2.0


In [5]:
# 假設 x 是你的變數
x = 42.0  # 或其他數字

# 確認 x 是否為整數
if isinstance(x, int):
    print(f"{x} 是整數")
else:
    print(f"{x} 不是整數")


42.0 不是整數


In [1]:
import math

# 假設你有一個數字 x
x = 10

math.log
# 確認結果是否為整數
if math.log10(x).is_integer():
    print("Y")
    # print(f"{x}的對數是整數: {int(log_result)}")
else:
    print("N")
    # print(f"{x}的對數不是整數: {log_result}")


Y


In [7]:
b = list(range(1100))
sum(b[-5:])

5485

In [1]:
class Sample:
    def __init__(self, a, b):
        self.a = a
        self.b = b
        print("__init__")
        
    def __enter__(self):
        add(self.a, self.b)
        print("in __enter__")
        return "Foo"
    def __exit__(self, exc_type, exc_val, exc_tb):
        print("in __exit__")
        
def add(a, b):
    return a + b


def get_sample(a, b):
    return Sample(a, b)
A = 1
B = 2


with get_sample(A, B) as sample:
    # print("Sample: ", sample)
    print("run some shit")

__init__
in __enter__
run some shit
in __exit__


In [8]:
class Sample():
    def __enter__(self):
        print('in enter')
        return self
    def __exit__(self, exc_type, exc_val, exc_tb):
        print('in exit')
        
        if exc_type != None:
            print("type: ", exc_type)
            print("val: ", exc_val)
            print("tb: ", exc_tb)
    def do_something(self):
        bar = 1 / 0
        return bar + 10
with Sample() as sample:
    print("a")
    sample.do_something()

in enter
a
in exit
type:  <class 'ZeroDivisionError'>
val:  division by zero
tb:  <traceback object at 0x7f8d3cafdf00>


ZeroDivisionError: division by zero

In [25]:
import pandas as pd

def save_reward_as_csv(List, log_dir=""):
    df = pd.DataFrame(List)
    df = df.set_axis(['duration', 'reward'], axis=1)
    df.to_csv(f"{log_dir}/monitor.csv", index=False)

a_list = []

log_dir = "./logs"

for i in range(100):
    a_list.append([i, i*10])
    
    if i % 10 == 0:
        
        save_reward_as_csv(a_list, log_dir=log_dir)

        df = pd.DataFrame(a_list)
        # df.columns.rename({"a", "b"})
        # df.rename("reward")
        # print(df)
    

In [23]:
# df.rename(columns={'0': 'Full Name', "1": "R"}, inplace=True)
df
df = df.set_axis(['V', 'W'], axis=1)
df

V    W
0    0    0
1    1   10
2    2   20
3    3   30
4    4   40
..  ..  ...
86  86  860
87  87  870
88  88  880
89  89  890
90  90  900

[91 rows x 2 columns]

In [11]:
ap = object()
ap.b = 0
ap.b


TypeError: can't set attributes of built-in/extension type 'object'

In [14]:
class obvervation:
    def __init__(self) -> None:
        self.arm = None
        self.cam = None
        self.interact_object = None

ob = obvervation()
print(ob.arm)

None


In [35]:
J = [0, 1, 2]
P = [5, 6, 7]
obvervation.arm = {"joint_angle" : J,
                        "end_point" : P}
obvervation.arm["joint_angle"]

[0, 1, 2]

In [45]:
aadf = obvervation.arm.keys()
# aadf[0]

a = list(obvervation.arm.values())
print(*a)

[0, 1, 2] [5, 6, 7]


In [44]:
a = [1, 2, 3]
b = [6, 7, 8]
c = [a, b]
c = [c, a]

# 將列表c中的元素逐層添加到一個新列表中
result = []
for sublist in c:
    result.extend(sublist)
    print(sublist)

print(result)


[[1, 2, 3], [6, 7, 8]]
[1, 2, 3]
[[1, 2, 3], [6, 7, 8], 1, 2, 3]


In [46]:
def unzip_list(key_list):
    result = []
    for sublist in key_list:
        result.extend(sublist)
    
    return result


In [48]:
a = [1, 2, 3]
b = [6, 7, 8]
c = [a, b]

d = unzip_list(list(obvervation.arm.values()))
d

[0, 1, 2, 5, 6, 7]

In [66]:
app = list(obvervation.arm.values())
app.append(a)
app

[[0, 1, 2], [5, 6, 7], [1, 2, 3]]

In [69]:
def is_bigger(a, b):
    c = a + b
    return a > b

a = 3
b = 5
if is_bigger(a, b):
    print("yes")
else:
    print("no")

no


In [72]:
import numpy as np
a = [1, 2, 3]
b = [6, 7, 8]
a_np = np.asarray(a)
b_np = np.asarray(b)
a_np + b_np


array([ 7,  9, 11])

In [57]:
a = [1, 2, 3]
b = [6, 7, 8]
c = [a, b]
c.append(a)
c

[[1, 2, 3], [6, 7, 8], [1, 2, 3]]

In [52]:
d = c.extend(a)
print(d)

None


In [74]:
a = {"arm": np.asarray([1, 2, 3]),
     "brm": np.asarray([1, 2, 3])
     }
a["arm"] + a["brm"]

array([2, 4, 6])

In [75]:
import random
random.randint(0, 1)

0

In [83]:
for i in range(10):
    print(random.randint(0, 2))

0
2
2
1
0
2
2
0
0
0


In [5]:
import numpy as np
distance = np.asarray(list(range(1, 10)))
reward = -  (distance ** 2     )
reward

array([ -1,  -4,  -9, -16, -25, -36, -49, -64, -81])

8
next_position [0.29999672 0.04999859 0.50025395]
good action
next_state [49.99566603597112, 34.87600246113904, 0.8133948494354953, 0.00037691997724081667, 54.327615031143225, 7.537967618110623e-10, 0.41991245528957843, 0.500351648294261, 0.4396867424109242, 0.42, 0.5, 0.44]
reward -2.2945091629307588e-07
distance 0.0004790103509247748
terminated True
truncated False
env finished


8
good action
next_state [49.971372162772994, 51.672741029313116, 3.2315226445357963, 0.0005957237768675618, 35.098552377698596, -5.090876893492936e-12, 0.41998819739837934, 0.5000102821235282, 0.23995316624154994, 0.42, 0.5, 0.24]
reward -2.4384243998215814e-09
distance 4.938040501880864e-05
terminated True
truncated False
env finished

In [ ]:
-0.27 -0.74 0.04
0.48 0.74 1

In [4]:
import numpy as np
a = [0, 1, 2]
b = [100, 1, 2]
a_np = np.asarray(a)
b_np = np.asarray(b)
(a_np - b_np).tolist()

[-100, 0, 0]

In [7]:
def unzip_list(key_list):
    result = []
    for sublist in key_list:
        result.extend(sublist)
    
    return result

state_list = [a, b]
state_list.append(a_np)

unzip_list(state_list)


[0, 1, 2, 100, 1, 2, 0, 1, 2]

In [1]:
import random


In [6]:
SEED = 525
random.seed(SEED) 

In [33]:
SEED = 525
random.seed(SEED)
for i in range(10):
    ran = random.randint(0, 5)
    print(ran)


4
0
3
1
5
1
4
0
1
4
